### ISSUE TITLE
Can't build on Apple Silicon with Xcode 27

### ISSUE THREAD

**Issue by HopeSuffers** [rt64/rt64#270]
Clean clone of main, standalone build on an M4, macOS 26.6.2, Xcode 27:

  cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug
  cmake --build build

dies at src/hle/rt64_projection.cpp:

```
src/contrib/hlslpp/include/hlsl++/platforms/scalar.h:553:89:
error: use of undeclared identifier 'labs'
```

Took a look. rt64_hlslpp.h forces HLSLPP_SCALAR on Apple Silicon, so we end up in scalar.h, which uses labs but only includes <math.h> and <stdint.h>. Xcode 27's libc++ doesn't drag in <stdlib.h> anymore, so it blows up. Intel Macs go through sse.h so they're fine.

Looks like hlslpp fixed this upstream in 05e747d0f, released in 3.9. The src/contrib/hlslpp submodule here is still pinned to 3.6 (6f5274c).

Building with -DCMAKE_CXX_FLAGS="-include stdlib.h" gets you past it for now.
